# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - "staged for next release ðŸ"
  - "pinned ðŸ“Œ"
  - "triage ðŸ˜°"
# Label to use when marking an issue as stale
staleLabel: "needs response ðŸ¤™"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  It's hard to keep track of everything. This issue has been automatically marked as stale because it has not had recent activity, neither from the team nor the community. It will be closed if no further activity occurs. Please consider adding additional info, volunteering to contribute a fix for this issue, or making a further case that this is important to you, the team, and the project as a whole. Thanks!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Issue closed after going stale. It can be re-opened if still relevant.
